### ISSUE TITLE
Create a unique icon for xSEED

### ISSUE THREAD

**Issue by dysbulic** [MetaFam/assets#1]
xSEED is SEED bridged to the xDAI network. It is a unique currency, and really should have a unique icon.

**Comment by mlibty** [comment]
I will try to do sth from my side...

**Comment by mlibty** [comment]
![xSEED3](https://user-images.githubusercontent.com/50373702/109365324-33d32a00-7891-11eb-830f-103c168d7cc5.png)
![xSEED1](https://user-images.githubusercontent.com/50373702/109365347-4188af80-7891-11eb-8bd1-9981254d45c4.png)
![xSEED2](https://user-images.githubusercontent.com/50373702/109365368-4e0d0800-7891-11eb-8444-96e9bb72961b.png)

**Comment by dysbulic** [comment]
Ultimately, the design I liked the best was [pΞTH's X made of SEED leaves](https://github.com/MetaFam/assets/blob/master/artists/p%CE%9ETH/xSEED.svg).
